favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#02C602'
    - '#A3D802'
    - '#010102'
    - '#BBB4D0'
    - '#D71F03'
  rhythmicContrast: 0
typography_spectrum: 0.5762986375484616
layout_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
name: Longboard Living Cancun
