name: Longboard Living Cancun
favicon: null
layout_spectrum: 0.17044756468385458
typography_spectrum: 0.5762986375484616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6667878087610006
  lightness: 0.2053876668214798
  saturation: 0.15497414697892964
  rhythmicContrast: 0.7923274540808052
purpose: []
